# Generated by Django 4.1.1 on 2022-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ultimo_nome',
            new_name='confirma_senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
