# Generated by Django 4.1.1 on 2022-10-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vale', '0002_rename_ultimo_nome_usuario_confirma_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirma_senha',
        ),
    ]
