# Generated by Django 4.1.1 on 2022-11-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vale', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='celular',
        ),
    ]
